import type { IClinicService } from '@/types/category';

export const mockClinicServices: IClinicService[] = [
  {
    id: 1,
    maDichVu: 'LAB.1000107',
    maDVBHYT: '579A7A6',
    coSo: 'Bệnh viện Thống Nhất',
    tenDichVu: 'Đo hoạt độ ALT (GPT) (Máu)_GỬI MEDIC',
    tenDVBHYT: 'Đo hoạt độ ALT (GPT)',
    loaiDichVu: 'Cận lâm sàng',
    nhomDichVu: 'Xét nghiệm',
    chiTietNhomDichVu: 'Xét nghiệm hóa sinh máu',
    donViTinh: 'Lần',
    giaDV: 150000,
    giaBHYT: 120000,
    maTheoTT: 'TT.ALT',
    tenTheoTT: 'Đo hoạt độ ALT',
    moGiaBHYT: true,
  },
  {
    id: 2,
    maDichVu: 'TT13_4545',
    maDVBHYT: '9B94E49',
    coSo: 'Bệnh viện Thống Nhất',
    tenDichVu: 'Virus test nhanh',
    tenDVBHYT: 'Test nhanh Virus',
    loaiDichVu: 'Cận lâm sàng',
    nhomDichVu: 'Xét nghiệm',
    chiTietNhomDichVu: 'Xét nghiệm vi sinh',
    donViTinh: 'Lần',
    giaDV: 238000,
    giaBHYT: 238000,
    maTheoTT: 'TT.TEST_NHANH',
    tenTheoTT: 'Test nhanh Virus',
    moGiaBHYT: true,
  },
  {
    id: 3,
    maDichVu: 'P12043',
    maDVBHYT: 'D660B7B',
    coSo: 'Bệnh viện Thống Nhất',
    tenDichVu: 'PT lại phình đại tràng bẩm sinh',
    tenDVBHYT: 'Phẫu thuật lại phình đại tràng',
    loaiDichVu: 'Phẫu thuật - thủ thuật',
    nhomDichVu: 'Phẫu thuật',
    chiTietNhomDichVu: 'PT Nhi',
    donViTinh: 'Lần',
    giaDV: 5000000,
    giaBHYT: 4500000,
    maTheoTT: 'TT.PT_PHINH',
    tenTheoTT: 'PT Phình đại tràng',
    moGiaBHYT: true,
  },
  {
    id: 4,
    maDichVu: 'T13212',
    maDVBHYT: '55CA7DB',
    coSo: 'Bệnh viện Thống Nhất',
    tenDichVu: 'Điện châm điều trị rối loạn tiêu hóa',
    tenDVBHYT: 'Điện châm',
    loaiDichVu: 'Phẫu thuật - thủ thuật',
    nhomDichVu: 'Thủ thuật',
    chiTietNhomDichVu: 'Y học cổ truyền (YHCT)',
    donViTinh: 'Lần',
    giaDV: 85000,
    giaBHYT: 75000,
    maTheoTT: 'TT.DIEN_CHAM',
    tenTheoTT: 'Điện châm',
    moGiaBHYT: true,
  },
];